### ISSUE TITLE
No installation instructions

### ISSUE THREAD

**Issue by ollyde** [Fluffcorn/ios-sticker-packs-app#1]
Hello, thanks for posting this you have saved my life with it.

But I can't get it to run. I'm getting constant compile errors.

What are the installation instructions?

**Comment by ansonl** [comment]
All you should have to do is clone the repository and build the project in Xcode. 

What compile errors are you getting?

**Comment by ollyde** [comment]
I fixed it by removing all the build libs and references to them. Try it.

**Comment by ansonl** [comment]
Good to hear you were able to resolve the issue. 

Yes, the project does include Google Firebase Analytics and Crash framework integration for those who want it so removing the Firebase references is the way to go if you do not need the integration or are doing testing.
