### ISSUE TITLE
'Firebase.h' file not found

### ISSUE THREAD

**Issue by tungnt1212** [Fluffcorn/ios-sticker-packs-app#3]
hi, I got this error when building product 
'Firebase.h' file not found
Could u please tell me how to fix that?

Sorry that I pull a wrong request 
<img width="1135" alt="Screen Shot 2019-06-02 at 7 52 34 PM" src="https://user-images.githubusercontent.com/29939047/58761573-119f6180-8570-11e9-853c-c472ecab58df.png">

**Comment by vanheinl** [comment]
Were you able to resolve the issue, if so, how? I’m getting the same issue. Thanks in advance

**Comment by ansonl** [comment]
The project comes with Firebase integrated. If you do not want firebase, comment out all code that references Firebase (you can command+shift+f to search all) and remove the import statement for `Firebase.h`.

This will remove Firebase references and the app will not use Firebase.

**Comment by vanheinl** [comment]
Awesome, got it. Thanks for the reply and the help, it’s very much appreciated!
